config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/back_office', as: 'rails_admin'
  resources :categories
  resources :accounts
  resources :transactions 
  get 'landing/welcome'
  root 'landing#welcome'
  get 'landing/about'
  devise_for :users
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @transactions = current_user.transactions
  end

  def pdf
    @transactions = current_user.transactions
  end

  def show
  end

  def new
    @transaction = Transaction.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @account = current_user.account
    @amount = @transaction.amount
    recipient = @transaction.recipient
    @user_recipient = User.find_by(email: recipient)
    DoTransaction.new(@account, @amount, recipient).transfer
    @transaction.category_id = params[:category_id]
    @transaction.user_id = current_user.id
    @transaction.account_id = current_user.account.id
      respond_to do |format|
      if @transaction.save
        UserMailer.received_money(current_user, @user_recipient, @amount).deliver_now
        UserMailer.sent_money(current_user, @user_recipient, @amount).deliver_now
        flash[:info] = "Please check your email to activate your account."
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @transaction.category_id = params[:category_id]
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 

  private

  
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:date, :amount, :user_id, :account_id, :recipient)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-6">
     <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Transasction Type!") %>
  </div>

  <div class="form-group col-md-6">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :transaction_date %>
  </div>

 <div class="form-group col-md-6">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :transaction_amount,:class => "form-control", :placeholder => 'Amount to Send' %>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :recipient %>
    <%= form.text_field :recipient, id: :transaction_recipient,:class => "form-control", :placeholder => 'Recipients Email' %>
  </div>

  <div align="center">
    <%= form.submit :class => 'btn btn-primary'%>
  </div>
<% end %>
</div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Transactions</h1>
<div class="table-responsive">
<table class='table'>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Amount</th>
      <th scope="col">Category</th>
      <th scope="col">User</th>
      <th scope="col">Recipient</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.date %></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.category&.name %></td>
        <td><%= transaction.user&.email %></td>
        <td><%= transaction.recipient %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div align="center">
</div>
</div>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @transaction.recipient %>
</p>

  <strong>User:</strong>
  <%= @transaction.user.email %>
</p>

<p>
  <strong>Account:</strong>
  <%= @transaction.account.number %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>