config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/back_office', as: 'rails_admin'
  resources :categories
  resources :accounts
  resources :transactions 
  get 'landing/welcome'
  root 'landing#welcome'
  get 'landing/about'
  devise_for :users
end

app/models/account.rb
class Account < ApplicationRecord
  include RailsAdminCharts
  belongs_to :user, optional: true
  has_many :transactions
  validates :number, uniqueness: true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
    respond_to do |format|
      format.html
      format.json { render :json => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    
  end

  # GET /accounts/1/edit
  def edit
    
  end

  def create
    @account = Account.new(account_params)
  
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:number, :balance, :user_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
  <div class="jumbotron">
    <%= form_with(model: account, local: true) do |form| %>
    <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>
      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, id: :account_number %>
  </div>

   <div class="form-group">
    <%= form.label :balance %>
    <%= form.text_field :balance, id: :account_balance %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :account_user_id %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-info' %>
  </div>
<% end %>
  </div>

app/views/accounts/edit.html.erb
<h1 class="display-4">Editing Account</h1>
<%= render 'form', account: @account %> <br>
<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>
</div>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>
<div class="table-responsive">
<table class='table'>
  <thead class="thead-dark">
    <tr>
      <th scope="col">Number</th>
      <th scope="col">Balance</th>
      <th scope="col">User</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.number %></td>
        <td><%= account.balance %></td>
        <td><%= account.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div align="center">

<%= link_to 'Create New Account', new_account_path ,:class => 'btn btn-success'%>
</div>
<br/>
</div>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<h1> Your Account Details</h1>
<div class="card border-success mb-3" style="max-width: 30rem;">
  <div class="card-header bg-transparent border-success">Your Account Details</div>
  <div class="card-body text-success">
    <div class="card-title">
      <strong>Number: </strong>
       <%= @account.number %>
     
    </div>
    <% if user_signed_in? && !current_user.try(:admin?) %>
      <div class="card-title">
      <strong>Balance:</strong>
      <%= @account.balance %>
    </div>
    <% end%>
    <div class="card-title">
      <strong>User:</strong>
      <%= @account.user.email %>
    </div>
   
  </div>
  <div class="card-footer bg-transparent border-success">
   <strong>Date Created:</strong>
  <%= @account.created_at %>
  </div>
</div>